### 连接造成的内存泄漏

##### 现象

内存占用率高，使用 jmap 查看

```shell
jmap -histo:live $pid
# 发现大量的 com.mysql.jdbc.NonRegisteringDriver$ConnectionPhantomReference

# dump内存详情，可以使用jprofile 等工具分析
jmap -dump:live,format=b,file=xx.dump $pid
```

dump 之后确认是大量连接在内存中，通过名字 ConnectionPhantomReference 关键字google，但没有得到满意的答案，于是关注 PhantomReference，官方文档描述(Java 8)：

```
Unlike soft and weak references, phantom references are not automatically cleared by the garbage collector as they are enqueued. An object that is reachable via phantom references will remain so until all such references are cleared or themselves become unreachable.
```

也就是说，内存不会自动释放，不过为啥有这么多对象，带着疑问看了一下源码，其实在AbandonedConnectionCleanupThread 中是有对其回收的线程，而且该线程保证会被启动，源码如下：

```java
// com.mysql.jdbc.NonRegisteringDriver 触发回收线程创建
static {
  try {
    Class.forName(AbandonedConnectionCleanupThread.class.getName());
  } catch (ClassNotFoundException e) {
    // ignore
  }
}

// com.mysql.jdbc.AbandonedConnectionCleanupThread 保证在类创建后后台线程被启动
static {
  cleanupThreadExcecutorService = Executors.newSingleThreadExecutor(new ThreadFactory() {
    public Thread newThread(Runnable r) {
      // ...
    }
  });
  cleanupThreadExcecutorService.execute(new AbandonedConnectionCleanupThread());
}

// com.mysql.jdbc.AbandonedConnectionCleanupThread#run
public void run() {
  for (;;) {
    try {
      checkContextClassLoaders();
      Reference<? extends ConnectionImpl> ref = NonRegisteringDriver.refQueue.remove(5000);
      if (ref != null) {
        try {
          ((ConnectionPhantomReference) ref).cleanup();
        } finally {
          NonRegisteringDriver.connectionPhantomRefs.remove(ref);
        }
      }

    } catch (InterruptedException e) {
      threadRef = null;
      return;

    } catch (Exception ex) {
      // Nowhere to really log this.
    }
  }
}
```

还好当时顺手打了jstack，于是判断该线程是否启动，发现没有对应的线程，但应用重启后是能是能找到对应的线程：

```
"Abandoned connection cleanup thread" #33 daemon prio=5 os_prio=0 tid=0x00007f4b9ca2d000 nid=0x2124 in Object.wait() [0x00007f4bd62ad000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        - locked <0x00007f4c02204808> (a java.lang.ref.ReferenceQueue$Lock)
        at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

可以推断出异常造成回收的线程退出，但上述代码run方法中其实对异常有处理，目前能想到的可能是碰到了 java.lang.Error

##### 思考

什么场景下使用 PhantomReference，用于解决什么问题？

